#pragma once

#include <server/common/Point.h>

#include <sdk/enum_cast.hpp>

#include <cstdint>

struct Direction final
{
	enum Value : uint8_t
	{
		Down = 0,
		BottomLeft,
		Left,
		TopLeft,
		Up,
		TopRight,
		Right,
		BottomRight
	};

	Point getIncrements() const
	{
		return _incrementsTable[enum_cast(_value)];
	}

	Direction getInverse() const
	{
		return _inverseTable[enum_cast(_value)];
	}

	void invert()
	{
		_value = _inverseTable[enum_cast(_value)];
	}

	constexpr Direction()
		: _value(Direction::Down)
	{ }

	constexpr Direction(Value value)
		: _value(value)
	{}

	constexpr static Direction lookUpSafe(Point from, Point to)
	{
		return _directionLookUpTable[(from.y - to.y) % LOOKUP_RANGE + LOOKUP_RANGE][(from.x - to.x) % LOOKUP_RANGE + LOOKUP_RANGE];
	}

	//Doesn't do % LOOKUP_RANGE so only use if sure it's in bounds (like movement)
	constexpr static Direction lookUpUnsafe(Point from, Point to)
	{
		return _directionLookUpTable[from.y - to.y + LOOKUP_RANGE][from.x - to.x + LOOKUP_RANGE];
	}

private:
	static constexpr Value _inverseTable[8] = { Direction::Up,   Direction::TopRight,   Direction::Right,Direction::BottomRight,
												  Direction::Down, Direction::BottomLeft, Direction::Left, Direction::TopLeft };

	static constexpr Point _incrementsTable[8] = { Point{0,-1},  Point{-1,-1},  Point{-1,0}, Point{-1,1},
												   Point{0,1},  Point{1,1},  Point{1,0}, Point{1,-1} };

	static constexpr int LOOKUP_RANGE = 16;

	//To calc this on compile time we'd need to calculate angles. The functions to do that aren't available on compile time. So this was calculated by the client which does it on static runtime, and copied here
	static constexpr Value _directionLookUpTable[LOOKUP_RANGE * 2 + 1][LOOKUP_RANGE * 2 + 1] =
	{
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft },
		{Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::Up, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::TopRight, Direction::TopRight, Direction::Up, Direction::TopLeft, Direction::TopLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Up, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left, Direction::Left, Direction::Left },
		{Direction::Right, Direction::Right, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::Left, Direction::Left },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft },
		{Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::BottomRight, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::Down, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft, Direction::BottomLeft }
	};

	Value _value;
};