#pragma once
//This file is automatically generated through RagnarokMasterTool

#include <cstdint>

enum class MonsterId : uint16_t
{
	AbysmalKnight,
	Gargoyle,
	BluePlant,
	GreenPlant,
	ShiningPlant,
	BlackMushroom,
	Khalitzburg,
	Raydric,
	RaydricArcher,
	GiantWhisper,
	Alice,
	Rideword,
	Last = Rideword,
	None = static_cast<uint16_t>(-1)
};
